-keep class com.kasari.update.** { *; }
-dontwarn com.kasari.update.**
-keepclassmembers class * extends android.app.Service { *; }
-keepclassmembers class * extends android.content.BroadcastReceiver { *; }
